#### 1. libraries upload

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#### 2. Data load

In [4]:
churm_df= pd.read_csv('https://raw.githubusercontent.com/Haroldgio28/Probabilidad_de_impago/main/data/case%202/Churn%20Modeling.csv')
churm_df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0


#### 3. Data exploration

In [10]:
# How many dimetions churm dataframe has?
'''
Churm dataframe hast 10.000 rows and 14 columns o variables
'''
churm_df.shape


(10000, 14)

In [ ]:
# Info about dataframe
'''
Info from crum dataframe shows rows number and a detailed description of it's 14 rows
it hasn't null values

'''
churm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


| Column    | Description              | Variable type | Data type |
|-----------|--------------------------|---------------|-----------|
| RowNumber | Unique id for every row  | N/A           | int       |
| CustomerId | Unique id for every customer | N/A | int |
| Surname | Surname | Qualitative nominal data | object |
| CreditScore | credit score for customer | Qantitative discrete data | int |
| Geography | Geographic location | Qualitative Nominal data | object |
| Gender | Gender | Qualitative binary data | int |
| Age | age | quantitative discrete data | int |
| Tenure | Tenure | Quantitative discrete data | int |

In [32]:
# Here we separate numeric and categorical variables from churm data
numeric_var = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']
categorical_var = ['Geography', 'Gender', 'HasCrCard', 'IsActiveMember', 'Exited']

# now we will change data type for categorical varibales due is a good practice on data description
'''
When we change data type on a categorical variable we can choose between objet ans category
category is more efficient
'''
for categ in categorical_var:
    churm_df[categ] = churm_df[categ].astype('category')

In [33]:
churm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype   
---  ------           --------------  -----   
 0   RowNumber        10000 non-null  int64   
 1   CustomerId       10000 non-null  int64   
 2   Surname          10000 non-null  object  
 3   CreditScore      10000 non-null  int64   
 4   Geography        10000 non-null  category
 5   Gender           10000 non-null  category
 6   Age              10000 non-null  int64   
 7   Tenure           10000 non-null  int64   
 8   Balance          10000 non-null  float64 
 9   NumOfProducts    10000 non-null  int64   
 10  HasCrCard        10000 non-null  category
 11  IsActiveMember   10000 non-null  category
 12  EstimatedSalary  10000 non-null  float64 
 13  Exited           10000 non-null  category
dtypes: category(5), float64(2), int64(6), object(1)
memory usage: 752.7+ KB


In [ ]:
# We explore how many unique values calumns has
churm_df['Tenure'].unique()

array([ 2,  1,  8,  7,  4,  6,  3, 10,  5,  9,  0])

In [19]:
churm_df['NumOfProducts'].unique()

array([1, 3, 2, 4])

In [20]:
churm_df['HasCrCard'].unique()

array([1, 0])

In [21]:
churm_df['Exited'].unique()

array([1, 0])